MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('1', 'Комедия');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('2', 'Драма');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('3', 'Мультфильм');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('4', 'Документальный');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('5', 'Боевик');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('6', 'Триллер');

MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('1', 'G');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('2', 'PG');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('3', 'PG-13');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('4', 'R');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('5', 'NC-17');