MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('1', 'Drama');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('2', 'Detective');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('3', 'Comedy');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('4', 'Documentary');

MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('1', 'G');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('2', 'PG');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('3', 'PG-13');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('4', 'R');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('5', 'NC-17');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('Win', 'Win in batle', '2001-01-01', '10', '4');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('Lose', 'Lose out batle', '2002-02-02', '20', '5');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('Postgres', 'Postgres VS H2', '2003-03-03', '30', '3');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('SQL', 'SQL and others...', '2004-04-04', '40', '2');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('DB', 'Different in DataBase', '2004-04-04', '40', '1');

INSERT INTO FILMS_GENRES (FILMS_ID, GENRE_ID)
VALUES ('1', '1');
INSERT INTO FILMS_GENRES (FILMS_ID, GENRE_ID)
VALUES ('1', '4');
INSERT INTO FILMS_GENRES (FILMS_ID, GENRE_ID)
VALUES ('2', '2');
INSERT INTO FILMS_GENRES (FILMS_ID, GENRE_ID)
VALUES ('2', '4');
INSERT INTO FILMS_GENRES (FILMS_ID, GENRE_ID)
VALUES ('3', '3');
INSERT INTO FILMS_GENRES (FILMS_ID, GENRE_ID)
VALUES ('3', '1');
INSERT INTO FILMS_GENRES (FILMS_ID, GENRE_ID)
VALUES ('4', '4');

INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Ivan', 'Ivan1991', 'ivan@mail.ru', '1991-01-01');
INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Hose', 'Hose1992', 'hose@ya.ru', '1992-02-02');
INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Vasya', 'Vasya1993', 'vasya@ya.ru', '1993-03-03');
INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Stepa', 'Stepa1994', 'stepa@ya.ru', '1994-04-04');
INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Pavel', 'Pavel1995', 'pavel@ya.ru', '1995-05-05');

INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('1', '2');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('1', '3');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('2', '1');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('2', '4');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('3', '5');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('4', '2');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('5', '3');

INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('1', '2', 'true');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('2', '1', 'false');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('3', '1', 'false');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('1', '3', 'true');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('1', '4', 'true');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('4', '1', 'true');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('1', '5', 'false');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('5', '1', 'false');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('2', '3', 'true');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS)
VALUES ('3', '2', 'true');