MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('1', 'Комедия');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('2', 'Драма');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('3', 'Мультфильм');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('4', 'Документальный');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('5', 'Боевик');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES ('6', 'Триллер');

MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('1', 'G');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('2', 'PG');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('3', 'PG-13');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('4', 'R');
MERGE INTO FILMS_RATING (RATING_ID, RATING_NAME)
    VALUES ('5', 'NC-17');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('Win', 'Win in batle', '2001-01-01', '10', '4');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('Lose', 'Lose out batle', '2002-02-02', '20', '5');

INSERT INTO FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('Postgres', 'Postgres VS H2', '2003-03-03', '30', '3');

INSERT INTO FILMS_GENRES (FILM_ID, GENRE_ID)
VALUES ('1', '1');
INSERT INTO FILMS_GENRES (FILM_ID, GENRE_ID)
VALUES ('1', '4');
INSERT INTO FILMS_GENRES (FILM_ID, GENRE_ID)
VALUES ('2', '2');
INSERT INTO FILMS_GENRES (FILM_ID, GENRE_ID)
VALUES ('3', '3');
INSERT INTO FILMS_GENRES (FILM_ID, GENRE_ID)
VALUES ('3', '1');

INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Ivan', 'Ivan1991', 'ivan@mail.ru', '1991-01-01');
INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Hose', 'Hose1992', 'hose@ya.ru', '1992-02-02');
INSERT INTO USERS (USER_LOGIN, USER_NAME, USER_EMAIL, BIRTHDATE)
VALUES ('Vasya', 'Vasya1993', 'vasya@ya.ru', '1993-03-03');

INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('1', '2');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('1', '3');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('2', '1');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('2', '3');
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES ('3', '2');

INSERT INTO FRIENDS (USER_ID, FRIEND_ID)
VALUES ('1', '2');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID)
VALUES ('2', '1');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID)
VALUES ('3', '1');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID)
VALUES ('1', '3');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID)
VALUES ('2', '3');
INSERT INTO FRIENDS (USER_ID, FRIEND_ID)
VALUES ('3', '2');